apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jobdbdump
spec:
  schedule: "* */4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql
            image: mysql:5.7.5
            command: ["/bin/sh","-c"]
            args: ["mysqldump --single-transaction -u $MYSQL_USER $MYSQL_DB -h $MYSQL_HOST > /var/lib/dump/`date '+%Y%m%d-%H:%M:%S'`.sql; mysql -u $MYSQL_USER -p$MYSQL_PWD $MYSQL_DB -e \"DELETE FROM lectures WHERE lastLecture < DATE_SUB(NOW(), INTERVAL $DAY_INTERVAL DAY)\""]
            volumeMounts:
            - mountPath: /var/lib/dump
              name: mysql-persistent-storage-dump
            env :
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DB
              value: "cluster"
            - name: MYSQL_PWD
              value: "password"
            - name: MYSQL_HOST
              value: "mysql"
            - name: DAY_INTERVAL
              value: "2"
          restartPolicy: OnFailure
          volumes:
          - name: mysql-persistent-storage-dump
            persistentVolumeClaim:
              claimName: mysql-pv-claim-dump