kind: Service
apiVersion: v1
metadata:
  name: collectdataservice
spec:
  selector:
    app: collectdata
  ports:
  # Porta accessibile all'interno del cluster dagli altri Pod
  - targetPort: 8005
    
    # Porta accessibile all'esterno
    port: 30006
  type: LoadBalancer