apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checkstatusjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: checkstatus
              image: checkstatus:v1
          restartPolicy: Never