apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dbconnector
  name: dbconnectordeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbconnector
  strategy: {}
  template:
    metadata:
      labels:
        app: dbconnector
    spec:
      containers:
      - image: dbconnector:v1
        imagePullPolicy: Never
        name: dbconnector
        ports:
        - containerPort: 8020