apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: collectdatahpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: collectdatadeployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50