apiVersion: batch/v1
kind: Job
metadata:
  name: jobdbdump 
spec:
  template:
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        command: ["/bin/sh","-c"]
        args: ["mysqldump --single-transaction -u $MYSQL_USER $MYSQL_DB -h $MYSQL_HOST > /var/lib/mysql/dump`date '+%Y%m%d'`.sql; mysql -u $MYSQL_USER -p$MYSQL_PWD $MYSQL_DB -e \"DELETE FROM lectures WHERE lettura < DATE_SUB(NOW(), INTERVAL $DAY_INTERVAL DAY)\""]
        volumeMounts:
        - mountPath: /var/lib/mysql/dump
          name: mysql-persistent-storage-dump
        env :
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_DB
          value: "cluster"
        - name: MYSQL_PWD
          value: "password"
        - name: MYSQL_HOST
          value: "mysql"
        - name: DAY_INTERVAL
          value: "7"
      restartPolicy: Never
      volumes:
      - name: mysql-persistent-storage-dump
        persistentVolumeClaim:
          claimName: mysql-pv-claim-dump