apiVersion: batch/v1
kind: Job
metadata:
  name: uploads3job
spec:
  template:
    spec:
      containers:
      - image: uploads3:v1
        imagePullPolicy: Never
        name: uploads3
        volumeMounts:
        - name: mysql-persistent-storage-dump
          mountPath: /app/dump
      restartPolicy: Never
      volumes:
      - name: mysql-persistent-storage-dump
        persistentVolumeClaim:
          claimName: mysql-pv-claim-dump