apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume-dump
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql/dump
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-dump
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20M
      