kind: Service
apiVersion: v1
metadata:
  name: dbconnectorservice
spec:
  selector:
    app: dbconnector
  ports:
  - protocol: "TCP"
    # Port accessible inside cluster
    port: 8020
    # Port to forward to inside the pod
    targetPort: 8020
  type: NodePort